### ISSUE TITLE
Ability to enqueue a task ahead of already-enqueued tasks?

### ISSUE THREAD

**Issue by mecampbellsoup** [procrastinate-org/procrastinate#698] opened 2022-11-03 20:47 UTC
I skimmed the docs and didn't see anything but - is there any existing feature where we could "short-circuit" already-enqueued tasks so that the next thing enqueued is taken off the queue and performed _next_?

**Comment by ewjoachim** [comment] 2022-11-03 21:36
Am I wrong if I suggest it's a duplicate of https://github.com/procrastinate-org/procrastinate/issues/386 ?

**Closed** 2024-01-06 20:37 UTC
