### ISSUE TITLE
SQL Migration `00.19.00_02_null_locks_excluded.sql` missing in 0.20.0 and 0.21.0

### ISSUE THREAD

**Issue by sebastian-hatala-leanix** [procrastinate-org/procrastinate#574] opened 2022-03-21 15:52 UTC
In the tags [0.20.0](https://github.com/procrastinate-org/procrastinate/releases/tag/0.20.0) and [0.21.0](https://github.com/procrastinate-org/procrastinate/releases/tag/0.21.0) the file [00.19.00_02_null_locks_excluded.sql](https://github.com/procrastinate-org/procrastinate/blob/main/procrastinate/sql/migrations/00.19.00_02_null_locks_excluded.sql) is missing.

As per my understanding, the migrations with pattern 00.19.* should be incremental upgrades to migrate from Procrastinate 0.19.x to a newer version.

**Comment by ewjoachim** [comment] 2022-03-23 08:39
You are right. The problem is that the file is named incorrectly :( When I merged the PR several months after writing it, I failed to check the name of the PR. It should have been a 0.22 as it was added to 0.23.

We really should tackle https://github.com/procrastinate-org/procrastinate/issues/251 :(

If we reintroduce the migration in a new version with a proper name, would it fix your case ?

**Comment by sebastian-hatala-leanix** [comment] 2022-03-23 08:44
Yes, that would be great!

**Closed** 2022-03-23 08:51 UTC

**Comment by ewjoachim** [comment] 2022-03-23 09:57
https://pypi.org/project/procrastinate/0.24.1/
